! GENERATED by tools/yl_runtime_gen.py from docs/m4/evidence/runtime-state-scan.json.
! Do not edit; edit the scan or the manifest and regenerate.
!
! The .glb scalars global_data reads PAST the adapter entry. Every one is a legacy global
! the adapter path would otherwise leave undefined; `alfa_p4` is the one -init=snan caught.
!
! Default-initialised rather than left undefined on purpose: this type is filled in one
! place and written in one place, and a component the parser forgets must read as a
! definite value rather than as whatever the stack held. The value being wrong is a bug
! the cross-path comparison can catch; the value being indeterminate is not.
module yl_problem_runtime_scalars

  use iso_fortran_env, only: int32, real64

  implicit none
  private

  type, public :: runtime_scalars_t
    real(real64) :: absorb = 0.0_real64   ! Global.f90:1058
    real(real64) :: alfa_p4 = 0.0_real64   ! Global.f90:1058
    integer(int32) :: balgor = 0   ! Global.f90:789
    real(real64) :: beeta1 = 0.0_real64   ! Global.f90:961
    real(real64) :: beeta2 = 0.0_real64   ! Global.f90:961
    real(real64) :: camif = 0.0_real64   ! Global.f90:1075
    real(real64) :: coefMpa = 0.0_real64   ! Global.f90:1062
    integer(int32) :: doubsig = 0   ! Global.f90:1062
    real(real64) :: dxmif = 0.0_real64   ! Global.f90:1075
    integer(int32) :: ECWPIPE = 0   ! Global.f90:815
    real(real64) :: epsMIFb = 0.0_real64   ! Global.f90:1075
    real(real64) :: ftcrack = 0.0_real64   ! Global.f90:1062
    real(real64) :: gamaMIF = 0.0_real64   ! Global.f90:1075
    integer(int32) :: Icaddmass = 0   ! Global.f90:1058
    integer(int32) :: ifixvar0_inpb = 0   ! Global.f90:1075
    real(real64) :: ifsgravity = 0.0_real64   ! Global.f90:1058
    integer(int32) :: ifswater = 0   ! Global.f90:1058
    integer(int32) :: ikindks = 0   ! Global.f90:1062
    integer(int32) :: kgmat = 0   ! Global.f90:815
    integer(int32) :: kinit = 0   ! Global.f90:762
    integer(int32) :: kstat = 0   ! Global.f90:833
    real(real64) :: ktan1 = 0.0_real64   ! Global.f90:1062
    real(real64) :: ktan2 = 0.0_real64   ! Global.f90:1062
    integer(int32) :: ndimnrt = 0   ! Global.f90:1062
    integer(int32) :: nextrf = 0   ! Global.f90:833
    integer(int32) :: nflow = 0   ! Global.f90:815
    integer(int32) :: ngaps = 0   ! Global.f90:880
    integer(int32) :: nhmat = 0   ! Global.f90:815
    integer(int32) :: ninistn = 0   ! Global.f90:762
    integer(int32) :: nlaymif = 0   ! Global.f90:1075
    integer(int32) :: nldfl = 0   ! Global.f90:815
    integer(int32) :: nlocalbeam = 0   ! Global.f90:1062
    integer(int32) :: nmass = 0   ! Global.f90:815
    integer(int32) :: nqmat = 0   ! Global.f90:815
    integer(int32) :: nswkw = 0   ! Global.f90:815
    integer(int32) :: nthmat = 0   ! Global.f90:833
    integer(int32) :: ntsmat = 0   ! Global.f90:833
    integer(int32) :: res_a = 0   ! Global.f90:1032
    integer(int32) :: res_f = 0   ! Global.f90:1032
    integer(int32) :: res_ms = 0   ! Global.f90:1032
    integer(int32) :: res_P = 0   ! Global.f90:1032
    integer(int32) :: res_rot = 0   ! Global.f90:1032
    integer(int32) :: res_s = 0   ! Global.f90:1032
    integer(int32) :: res_T = 0   ! Global.f90:1032
    integer(int32) :: res_u = 0   ! Global.f90:1032
    integer(int32) :: res_v = 0   ! Global.f90:1032
    integer(int32) :: stabpw = 0   ! Global.f90:789
    real(real64) :: stiff_p4 = 0.0_real64   ! Global.f90:1058
    real(real64) :: swlifs2006 = 0.0_real64   ! Global.f90:1058
    real(real64) :: theta1 = 0.0_real64   ! Global.f90:961
    real(real64) :: toth = 0.0_real64   ! Global.f90:1058
    integer(int32) :: upliftin = 0   ! Global.f90:789
    integer(int32) :: uwcpl = 0   ! Global.f90:815
  end type runtime_scalars_t

end module yl_problem_runtime_scalars
