 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
 Iafile icond ipdchk ising
  0  0  1  1
