#!/usr/bin/env python3
"""Generate the runtime-scalar carrier and the two code blocks that fill and write it.

The runtime state manifest covers arrays. Scalars are the other half and there are 80 of
them: legacy globals read from `.glb` past the adapter entry, which the adapter path
therefore leaves undefined. `alfa_p4` is the one that announced the class -- under
-init=snan the adapter path trapped on `if (alfa_p4 > 0)` in modf_element_lib while the
legacy path ran clean.

Eighty hand-written components, eighty assignments and eighty writes would be eighty
chances to mistype one, and a mistyped one is silent. So all three are GENERATED from
tools/yl_runtime_scan.py's enumeration, the same way src/state/yl_state_dump.f90 is
generated from the M2 map:

  src/problem/yl_problem_runtime_scalars.f90   the carrier type
  src/adapter/yl_adapter_scalars.inc           parse_glb: carrier <- its own locals
  src/runtime/yl_runtime_scalars.inc           commit:    legacy global <- carrier

`text` is excluded by name: it is the scratch buffer every title record is read into, not
state. Nothing reads it after the read that filled it.

Usage:
    tools/yl_runtime_gen.py            # regenerate all three
    tools/yl_runtime_gen.py --check    # fail if any is stale
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCAN = ROOT / "docs/m4/evidence/runtime-state-scan.json"
EXCLUDE = {"text"}

FKIND = {"integer": "integer(int32)", "real": "real(real64)", "character": "character(len=20)"}
LKIND = {"integer": "ink", "real": "irk"}

BANNER = "! GENERATED by tools/yl_runtime_gen.py from docs/m4/evidence/runtime-state-scan.json.\n! Do not edit; edit the scan or the manifest and regenerate.\n"


PARSE_GLB = ROOT / "src/adapter/yl_adapter_model.f90"


def parse_glb_locals() -> set[str]:
    """Names declared in parse_glb's own declaration section.

    The scan spans ALL of global_data, whose internal routines (read_element and friends)
    read scalars parse_glb never sees -- f0, i0, ipoin. Generating an assignment for those
    produced a fill referring to names that do not exist. The carrier can only be filled
    from what the parser actually read, so the generated fill is intersected with this set
    and the remainder is recorded in the manifest as not carried, with its reason.
    """
    txt = PARSE_GLB.read_text()
    i = txt.index("  subroutine parse_glb(")
    j = txt.index("\n    ios = 0", i) if "\n    ios = 0" in txt[i:i + 40000] else i + 40000
    head = txt[i:j]
    names = set()
    for l in head.split("\n"):
        b = l.split("!")[0]
        if "::" not in b:
            continue
        for m in re.finditer(r"\b([A-Za-z_]\w*)\b", b.split("::", 1)[1]):
            names.add(m.group(1).lower())
    return names


def scalars() -> list[dict]:
    doc = json.loads(SCAN.read_text(encoding="utf-8"))
    out = [s for s in doc["scalar_candidates"]
           if s["symbol"].lower() not in EXCLUDE and s["type"] in FKIND]
    out.sort(key=lambda s: s["symbol"].lower())
    return out


def carried(rows: list[dict]) -> list[dict]:
    have = parse_glb_locals()
    return [r for r in rows if r["symbol"].lower() in have]


def carrier(rows: list[dict]) -> str:
    body = "".join(
        f"    {FKIND[r['type']]} :: {r['symbol']} = {'0' if r['type']=='integer' else ('0.0_real64' if r['type']=='real' else chr(39)+chr(39))}"
        f"   ! Global.f90:{r['line']}\n"
        for r in rows)
    return f"""{BANNER}!
! The .glb scalars global_data reads PAST the adapter entry. Every one is a legacy global
! the adapter path would otherwise leave undefined; `alfa_p4` is the one -init=snan caught.
!
! Default-initialised rather than left undefined on purpose: this type is filled in one
! place and written in one place, and a component the parser forgets must read as a
! definite value rather than as whatever the stack held. The value being wrong is a bug
! the cross-path comparison can catch; the value being indeterminate is not.
module yl_problem_runtime_scalars

  use iso_fortran_env, only: int32, real64

  implicit none
  private

  type, public :: runtime_scalars_t
{body}  end type runtime_scalars_t

end module yl_problem_runtime_scalars
"""


def fill(rows: list[dict]) -> str:
    body = "".join(f"  existence%scalars%{r['symbol']} = {r['symbol']}\n" for r in rows)
    return (BANNER + "! parse_glb: copy the .glb scalars it already read into the carrier.\n"
            + body)


def use_block(rows: list[dict]) -> str:
    """commit's `use` for the scalars it writes.

    Generated rather than hand-merged into the existing `use global_var, only:` list: a
    second `only` clause for the same module is legal Fortran and keeps the generated set
    exactly the scan's set, so a scalar cannot be written without being imported or
    imported without being written.
    """
    mods: dict[str, list[str]] = {}
    for r in rows:
        mods.setdefault(r.get("module") or "global_var", []).append(r["symbol"])
    out = BANNER + "! commit: import the legacy scalars the manifest's scalar half writes.\n"
    for mod, names in sorted(mods.items()):
        chunk = sorted(names, key=str.lower)
        for i in range(0, len(chunk), 6):
            part = ", ".join(chunk[i:i + 6])
            cont = ", &" if i + 6 < len(chunk) else ""
            head = f"  use {mod}, only: " if i == 0 else "    "
            out += f"{head}{part}{cont}\n"
    return out


def write(rows: list[dict]) -> str:
    body = "".join(
        f"    {r['symbol']} = "
        + (f"int(existence%scalars%{r['symbol']}, ink)" if r["type"] == "integer"
           else (f"real(existence%scalars%{r['symbol']}, irk)" if r["type"] == "real"
                 else f"existence%scalars%{r['symbol']}"))
        + "\n" for r in rows)
    return (BANNER + "! commit: the WRITE phase's scalar half of the runtime state manifest.\n"
            + body)


TARGETS = {
    "src/problem/yl_problem_runtime_scalars.f90": carrier,
    "src/adapter/yl_adapter_scalars.inc": fill,
    "src/runtime/yl_runtime_scalars.inc": write,
    "src/runtime/yl_runtime_scalars_use.inc": use_block,
}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    rows = carried(scalars())
    stale = []
    for rel, fn in TARGETS.items():
        want = fn(rows)
        p = ROOT / rel
        if a.check:
            if not p.is_file() or p.read_text(encoding="utf-8") != want:
                stale.append(rel)
        else:
            p.write_text(want, encoding="utf-8")
    if a.check:
        for s in stale:
            print(f"FAIL stale: {s}")
        print(f"RUNTIME-SCALARS {'FAIL' if stale else 'PASS'}: {len(rows)} scalars, "
              f"{len(stale)} stale of {len(TARGETS)}")
        return 1 if stale else 0
    total = len(scalars())
    print(f"generated {len(TARGETS)} files for {len(rows)} carried scalars "
          f"({total - len(rows)} of {total} are read by global_data's internal routines, "
          f"not by parse_glb, and are recorded in the manifest instead)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
